name: Update GH-pages
on:
  workflow_dispatch:

permissions: write-all

jobs:
  update:
    name: Update GH pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-gap@v3
      - uses: gap-actions/update-gh-pages@v1
