name: Test (GAP)
on:
  workflow_call:
    inputs:
      gap-version:
        type: string
      mode:
        default: 'default'
        type: string
      warnings-as-errors:
        default: true
        type: boolean
      complete:
        default: false
        type: boolean

jobs:
  test:
    name: "Test GAP (version: ${{ inputs.gap-version }}, mode: ${{ inputs.mode }})"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    container:
      image: ghcr.io/stertooy/gda-image:${{ inputs.gap-version }}-${{ inputs.mode == 'loadall' && 'full' || 'slim' }}

    steps:

      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Add custom GAP root"
        run: ln -f -s $PWD /tmp/gaproot/pkg/

      - name: "Run GAP tests"
        uses: stertooy/run-gap-tests@v1
        with:
          complete: ${{ inputs.complete }}
          mode: ${{ inputs.mode }}
          warnings-as-errors: ${{ inputs.warnings-as-errors }}
